#!/bin/sh

## Thanks to Wakkymike for help ;)

print_dalek()
{
	echo "██████╗░░█████╗░██╗░░░░░███████╗██╗░░██╗  ██╗██████╗░░█████╗░"
	echo "██╔══██╗██╔══██╗██║░░░░░██╔════╝██║░██╔╝  ██║██╔══██╗██╔══██╗"
	echo "██║░░██║███████║██║░░░░░█████╗░░█████═╝░  ██║██████╔╝██║░░╚═╝"
	echo "██║░░██║██╔══██║██║░░░░░██╔══╝░░██╔═██╗░  ██║██╔══██╗██║░░██╗"
	echo "██████╔╝██║░░██║███████╗███████╗██║░╚██╗  ██║██║░░██║╚█████╔╝"
	echo "╚═════╝░╚═╝░░╚═╝╚══════╝╚══════╝╚═╝░░╚═╝  ╚═╝╚═╝░░╚═╝░╚════╝░"
}

dalek_start()
{
	echo "Dalek IRC Services is booting"
	screen -S dalek-serv -d -m php src/dalek
	echo "Launching services...";
	if screen -list | grep dalek-serv ; then
		echo "Launched!"
		echo "Connecting..."
		dalek_rpc_server
	else
		echo "Failed"
		dalek_stop
	fi
}

dalek_stop()
{
	echo "Dalek IRC Services is stopping..."
	screen -ls | grep dalek-serv | cut -d. -f1 | awk '{print $1}' | xargs kill
	screen -ls | grep dalek-rpc-serv | cut -d. -f1 | awk '{print $1}' | xargs kill
	echo "Stopped"
}

dalek_rpc_server()
{
	echo "Booting RPC Server on 127.0.0.1:1024"
	screen -S dalek-rpc-serv -d -m php -S 127.0.0.1:1024 -t src/RPC/
	if screen -ls | grep dalek-rpc-serv ; then
		echo "RPC Server online"
	else
		echo "Failed"
		dalek_stop
	fi
}
dalek_restart()
{
	echo "Dalek IRC Services is restarting..."
	dalek_stop
	dalek_start
}

if [ "$1" = "start" ] ; then
	print_dalek
	dalek_start

elif [ "$1" = "restart" ] ; then
	dalek_restart

elif [ "$1" = "stop" ] ; then
	dalek_stop
	
elif [ "$1" = "genlinkblock" ] ; then
	php scripts/genlinkblock

elif [ "$1" = "rehash" ] ; then
	curl -s --insecure -X POST -d '{"jsonrpc": "2.0", "method": "rehash", "params": {"server": "services.valware.uk"}, "id": 123}' http://localhost:1024/api >> /dev/null

else
	echo "Command syntax: ./dalek start|restart|stop|rehash"
fi


